# Generated by Django 2.0.2 on 2018-03-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userpage', '0004_auto_20180228_1552'),
        ('article', '0016_comment_invalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Comment')),
                ('mention_user', models.ManyToManyField(to='userpage.Profile')),
            ],
        ),
    ]
