# Generated by Django 2.0.2 on 2018-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='unread',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='Y', max_length=8),
        ),
    ]
