# Generated by Django 2.0.2 on 2018-02-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=64),
        ),
    ]
