# Generated by Django 2.0.2 on 2018-02-24 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Section',
            },
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.Section'),
        ),
    ]
