# Generated by Django 2.0.2 on 2018-02-24 03:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180224_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=128)),
                ('mail', models.CharField(max_length=1024)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', tinymce.models.HTMLField()),
                ('ip', models.GenericIPAddressField()),
                ('clickcount', models.IntegerField(default=0)),
                ('refer', models.CharField(default='none', max_length=5096)),
                ('agent', models.CharField(default='none', max_length=5096)),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
