# Generated by Django 2.0.2 on 2018-02-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180226_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
    ]
