# Generated by Django 2.0.2 on 2018-02-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_auto_20180226_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='unread',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
