# Generated by Django 2.0.2 on 2018-03-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_auto_20180228_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
