# Generated by Django 2.0.2 on 2018-03-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0006_auto_20180303_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point_record', models.IntegerField()),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('publish', '发布文章'), ('comment', '发表评论'), ('commented', '文章被评论')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
