# Generated by Django 2.0.2 on 2018-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='wechat',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='weibo',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='point',
            name='event',
            field=models.CharField(choices=[('publish', '发布文章'), ('comment', '发表评论'), ('commented', '文章被评论'), ('register', '新用户注册')], max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
