# Generated by Django 2.0.2 on 2018-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_auto_20180305_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
